import ClientOnly from './components/ClientOnly'
import Navbar from './components/Navbar/Navbar'
import Modal from './components/modals/Modal'
import './globals.css'
import { Nunito } from 'next/font/google'

const font = Nunito({ subsets: ['latin'] })

export const metadata = { 
  title: 'Airbnb',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly >
          <Modal isOpen={ true} actionLabel='Submit' title='World' />
           <Navbar/>
        </ClientOnly>
       
        {children}</body>
    </html>
  )
}
